### PR TITLE
rwc2022: fix: Add large search radius

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by PetervDooren** [comment]
@ar13pit, what was the reason you added the large radius? Do you want to request all entities in the worldmodel? Previously this could be done by sending radius=0 but not anymore. Is that the reason for this change?

**Comment by MatthijsBurgh** [comment]
@PetervDooren You changed it 😉 in https://github.com/tue-robotics/ed/pull/94

**Comment by MatthijsBurgh** [comment]
@ar13pit Needs to give the final answer. But I think it is.

**Comment by ar13pit** [comment]
The API broke somewhere and that was causing an issue in querying the people within a specific constraint. So as a safe default, setting the search space to infinity works.

**Comment by ar13pit** [comment]
I think the radius argument was not working at all

**Comment by MatthijsBurgh** [comment]
Comments of @ar13pit confirm the situation. So this PR can be approved.

**Pull request merged**
